import { Router, type IRouter } from "express";
import healthRouter from "./health";
import logsRouter from "./logs";
import cyclesRouter from "./cycles";
import insightsRouter from "./insights";
import dashboardRouter from "./dashboard";
import chatRouter from "./chat";
import journalRouter from "./journal";
import bodyMapRouter from "./bodyMap";
import reportCardRouter from "./reportCard";
import cycleTwinRouter from "./cycleTwin";
import timeCapsuleRouter from "./timeCapsule";
import cycleMarkersRouter from "./cycleMarkers";
import periodPredictorRouter from "./periodPredictor";
import stressSleepRouter from "./stressSleepImpact";
import cycleComparisonRouter from "./cycleComparison";
import quizContextRouter from "./quizContext";
import symptomHeatmapRouter from "./symptomHeatmap";

const router: IRouter = Router();

router.use(healthRouter);
router.use(logsRouter);
router.use(cyclesRouter);
router.use(insightsRouter);
router.use(dashboardRouter);
router.use(chatRouter);
router.use(journalRouter);
router.use(bodyMapRouter);
router.use(reportCardRouter);
router.use(cycleTwinRouter);
router.use(timeCapsuleRouter);
router.use(cycleMarkersRouter);
router.use(periodPredictorRouter);
router.use(stressSleepRouter);
router.use(cycleComparisonRouter);
router.use(quizContextRouter);
router.use(symptomHeatmapRouter);

export default router;
